import builtins from 'builtin-modules';

export const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// The Prettier plugin is a second thing built out of this source: a module a
// vault's formatter loads, not something Obsidian ever sees. It lives in its own
// module so the test that loads the built file from outside the repo builds it
// with these options and not a copy of them.
//
// ESM because that is what a `.prettierrc` plugin entry is loaded as. Prettier's
// markdown plugin is bundled in rather than left external, because the file is
// loaded from the vault, and a vault has no `node_modules` for an import of
// `prettier` to resolve against — left external, the plugin fails to load and
// the vault's format run formats nothing. Bundling it costs no correctness:
// Prettier takes the printer from whichever plugin supplied the parser, and
// this plugin supplies both, so the printer it carries is the one that runs.
// And it pins the vault's markdown formatting to this repo's Prettier, whatever
// version `npx` happens to resolve.
/**
 * @param {boolean} prod
 * @returns {import('esbuild').BuildOptions}
 */
export function pluginBuildOptions(prod) {
  return {
    banner: { js: banner },
    entryPoints: ['src/prettier-plugin.ts'],
    bundle: true,
    external: [...builtins],
    platform: 'node',
    format: 'esm',
    target: 'es2020',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'prettier-plugin.mjs',
    minify: false,
  };
}
